runtime: go
api_version: go1.9

default_expiration: "2s"

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
  secure: always

- url: /push.js
  static_files: js/push.js
  upload: js/push.js
  secure: always

- url: /sitemap.xml
  static_files: xml/sitemap.xml
  upload: xml/sitemap.xml
  secure: always

- url: /manifest.json
  mime_type: application/manifest+json
  static_files: json/manifest.json
  upload: json/manifest.json
  secure: always

- url: /robots.txt
  static_files: txt/robots.txt
  upload: txt/robots.txt
  secure: always

- url: /(.*\.html)$
  static_files: html/\1
  upload: html/.\.html$
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /html
  static_dir: html
  secure: always

- url: /json
  static_dir: json
  secure: always

- url: /style
  static_dir: style
  secure: always

# cron
- url: /api/cron
  secure: always
  login: admin
  script: _go_app

# ヘルスチェック
- url: /api/health
  secure: always
  login: admin
  script: _go_app

# クリーニング
- url: /api/cleanup
  secure: always
  login: admin
  script: _go_app

# テストコマンド
- url: /api/dummy
  secure: always
  login: admin
  script: _go_app

# データ移行用のコマンド
- url: /api/mainte
  secure: always
  login: admin
  script: _go_app

- url: /.*
  script: _go_app
  secure: always
