runtime: go
api_version: go1.9

default_expiration: "2s"

handlers:
- url: /
  static_files: resources/html/index.html
  upload: resources/html/index.html
  secure: always

- url: /push.js
  static_files: resources/js/push.js
  upload: resources/js/push.js
  secure: always

- url: /sitemap.xml
  static_files: resources/xml/sitemap.xml
  upload: resources/xml/sitemap.xml
  secure: always

- url: /manifest.json
  mime_type: application/manifest+json
  static_files: resources/json/manifest.json
  upload: resources/json/manifest.json
  secure: always

- url: /robots.txt
  static_files: resources/txt/robots.txt
  upload: resources/txt/robots.txt
  secure: always

- url: /(.*\.html)$
  static_files: resources/html/\1
  upload: resources/html/.\.html$
  secure: always

- url: /js
  static_dir: resources/js
  secure: always

- url: /img
  static_dir: resources/img
  secure: always

- url: /html
  static_dir: resources/html
  secure: always

- url: /json
  static_dir: resources/json
  secure: always

- url: /style
  static_dir: resources/style
  secure: always

# 管理者用非公開API
- url: /admin/.*
  secure: always
  login: admin
  script: _go_app

- url: /.*
  script: _go_app
  secure: always
